### ISSUE TITLE
Two screenshots are being taken when passing WebDriver driver to the test constructor using @SingleSession 

### ISSUE THREAD

**Issue by vicajoy** [bonigarcia/selenium-jupiter#93] opened 2020-12-03 14:52 UTC
I am using `@SingleSession` to run tests in one browser. When I pass a driver of WebDriver type, two screenshots are being taken after a test failure. But passing a driver of a specific type (for instance, ChromeDriver), it works fine.

Used the following test taken from your [examples](https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/singlessession/OrderedMultipleJupiterTest.java):

    private WebDriver driver;

    FailureCreatesScreenshotTest(WebDriver driver) {
        this.driver = driver;
    }

    @Test
    @Order(1)
    void testStep1() {
        step1(driver);
    }

    @Test
    @Order(2)
    void testStep2() {
        step2(driver);
    }

    private void step1(WebDriver driver) {
        driver.get("https://bonigarcia.github.io/selenium-jupiter/");
        assertTrue(driver.getTitle().contains("JUnit 5 extension for Selenium"));
    }

    private void step2(WebDriver driver) {
        WebElement about = driver.findElement(By.linkText("About"));
        about.click();
        assertFalse(about.isDisplayed());
    }

Used the following system properties in the build.gradle:

`"sel.jup.screenshot.at.the.end.of.tests"`, `"whenfailure" ` 
`"sel.jup.screenshot.format"`, `"png" ` 
`"sel.jup.output.folder"`, `"./build/screenshots"`

**Comment by bonigarcia** [comment] 2021-01-26 14:28
This should be fixed in version 3.4.0, just released.

**Closed by bonigarcia** 2021-01-26 14:28 UTC
Labels: bug

**Comment by vicajoy** [comment] 2021-02-02 11:07
Hi, @bonigarcia. Thanks for fixing the issue. I used the `selenium-jupiter-3.4.0` version to replace the `InternetExplorerDriver` with `WebDriver` but encountered issues when running tests on Windows. 
Please note that tests work fine on Chrome, Firefox, Edge browsers on Mac.
 
 > GoogleSearchTest > testBasicSearch(WebDriver) FAILED
  >     org.junit.jupiter.api.extension.ParameterResolutionException at ExecutableInvoker.java:239
   >         Caused by: io.github.bonigarcia.seljup.SeleniumJupiterException at SeleniumExtension.java:404
    >             Caused by: com.github.dockerjava.api.exception.DockerClientException at DefaultDockerClientConfig.java:107
 
Also, the 64-bit of Internet Explorer is being opened starting from the `selenium-jupiter-3.3.5` version despite the fact that I use
  `WebDriverManager.iedriver().arch32().setup();` to setup the 32-bit IE. 
Everything works on the `selenium-jupiter-3.3.4` version that I am using now (both on Windows and Mac).

**Comment by bonigarcia** [comment] 2021-02-02 15:24
Are you trying to use IExplorer in Docker, right? In that case, you need to build the Docker image by yourself (following this [tutorial](https://github.com/aerokube/windows-images)). Due to Windows licensing, that Docker image is not in Docker Hub (see [doc](https://bonigarcia.github.io/selenium-jupiter/#internet-explorer-2)).

**Comment by vicajoy** [comment] 2021-02-02 15:34
@bonigarcia, actually I am running locally, not on a Docker image. As I mentioned in my previous comment, everything works on the `selenium-jupiter-3.3.4` version. The tests are throwing the exception on the last version: `selenium-jupiter-3.4.0`.  

Also, the 64-bit of Internet Explorer is being opened starting from the `selenium-jupiter-3.3.5` version despite the fact that I use
`WebDriverManager.iedriver().arch32().setup();` to setup the 32-bit IE.

**Comment by bonigarcia** [comment] 2021-02-02 15:37
In that case, it should be a different issue. Could you please open a new issue about it? Please, follow the issue template to report the traces and so on, which is very important to find out the cause.
